[workspace]
resolver = "2"
members = [ "crawlspace-macro","crawlspace" , "crawlspace-proto", "crawlspace-proto-1_8"]

[profile.release-stripped]
inherits = "release"
strip = "symbols"

[profile.release-lto]
inherits = "release-stripped"
lto = true
