[workspace]
resolver = "2"
members = [ "crawlspace-macro","crawlspace", "crawlspace-slime"]

[profile.release-stripped]
inherits = "release"
strip = "symbols"

[profile.release-lto]
inherits = "release-stripped"
lto = true
