[package]
name = "crawlspace-proto-1_8"
version = "0.1.0"
edition = "2024"

[dependencies]
crawlspace-macro = { path = "../crawlspace-macro" }
crawlspace-proto = { path = "../crawlspace-proto" }

bytes = "1.10.1"
tokio = { version = "1.47.1", features = ["io-util", "net", "time"] }
tracing = "0.1.41"
