[package]
name = "crawlspace-proto"
version = "0.1.0"
edition = "2024"

[dependencies]
bitfield-struct = "0.11.0"
byteorder = "1.5.0"
serde = { version = "1.0.219", features = ["derive"] }
thiserror = "2.0.16"
uuid = "1.18.0"
